name: vim

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - main
    paths:
      - "**/*.vim"
      - "**/*.vimspec"
      - ".github/workflows/vim.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.vim"
      - "**/*.vimspec"
      - ".github/workflows/vim.yml"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        version:
          - nightly
          - v8.2.0235
          - v8.1.2424
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: "${{ matrix.version }}"
      - name: Fix %TEMP% on Windows
        shell: pwsh
        run: |
          # https://github.com/actions/virtual-environments/issues/712
          echo "TMP=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV
          echo "TEMP=$env:USERPROFILE\AppData\Local\Temp" >> $env:GITHUB_ENV
        if: runner.os == 'Windows'
      - name: Run tests
        run: |
          ./vim-themis/bin/themis
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
